WARNING:py.warnings:E:\languages\Python3.11\Lib\asyncio\base_events.py:1907: RuntimeWarning: coroutine 'final_method' was never awaited
  handle = self._ready.popleft()

WARNING:py.warnings:E:\languages\Python3.11\Lib\asyncio\base_events.py:1923: RuntimeWarning: coroutine 'final_method' was never awaited
  handle = None  # Needed to break cycles when an exception occurs.

INFO:root:procces has been completed and unique directory has been deleted.
INFO:root:procces has been completed and unique directory has been deleted.
INFO:root:procces has been completed and unique directory has been deleted.
ERROR:root:Error during downloading video from youtube: [0;31mERROR:[0m [youtube] 8-eCvn1gWIg: Requested format is not available. Use --list-formats for a list of available formats
ERROR:root:Error in final method: Error during downloading video from youtube.
INFO:root:Translation started...
INFO:root:Translation package from en to es is already installed.
INFO:root:Translation completed.
INFO:root:Model loaded and text to speech started successfully.
INFO:TTS.vc.modules.freevc.wavlm.wavlm:WavLM Config: {'extractor_mode': 'layer_norm', 'encoder_layers': 24, 'encoder_embed_dim': 1024, 'encoder_ffn_embed_dim': 4096, 'encoder_attention_heads': 16, 'activation_fn': 'gelu', 'layer_norm_first': True, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'feature_grad_mult': 1.0, 'normalize': True, 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.0, 'dropout_input': 0.0, 'dropout_features': 0.0, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': 'static', 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': 'static', 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'relative_position_embedding': True, 'num_buckets': 320, 'max_distance': 800, 'gru_rel_pos': True}
WARNING:py.warnings:E:\languages\Python3.11\Lib\site-packages\TTS\vc\models\freevc.py:496: UserWarning: PySoundFile failed. Trying audioread instead.
  wav, _ = librosa.load(wav, sr=self.config.audio.input_sample_rate)

WARNING:py.warnings:E:\languages\Python3.11\Lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

ERROR:root:Error during Text to Speech conversion: [Errno 2] No such file or directory: './static/process_videos\\f3df2c43-7c8d-4046-8d62-a64b6d73a7b7\\translated_audio\\Sigma Speed \U0001f5fffinalaudio.wav'
ERROR:root:Error in final method: Error during Text to Speech conversion.
INFO:root:Translation started...
INFO:root:Translation package from en to es is already installed.
INFO:root:Translation completed.
INFO:root:Model loaded and text to speech started successfully.
INFO:TTS.vc.modules.freevc.wavlm.wavlm:WavLM Config: {'extractor_mode': 'layer_norm', 'encoder_layers': 24, 'encoder_embed_dim': 1024, 'encoder_ffn_embed_dim': 4096, 'encoder_attention_heads': 16, 'activation_fn': 'gelu', 'layer_norm_first': True, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'feature_grad_mult': 1.0, 'normalize': True, 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.0, 'dropout_input': 0.0, 'dropout_features': 0.0, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': 'static', 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': 'static', 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'relative_position_embedding': True, 'num_buckets': 320, 'max_distance': 800, 'gru_rel_pos': True}
WARNING:py.warnings:E:\languages\Python3.11\Lib\site-packages\TTS\vc\models\freevc.py:496: UserWarning: PySoundFile failed. Trying audioread instead.
  wav, _ = librosa.load(wav, sr=self.config.audio.input_sample_rate)

WARNING:py.warnings:E:\languages\Python3.11\Lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

ERROR:root:Error during Text to Speech conversion: [Errno 2] No such file or directory: './static/process_videos\\f7635910-615f-4909-b142-f097f6105888\\translated_audio\\Sniper training, proved hes the best\U0001f3af #movie #seriesfinalaudio.wav'
ERROR:root:Error in final method: Error during Text to Speech conversion.
